# Generated by Django 3.2.12 on 2023-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_trendsmall', '0002_laptops'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='oldprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
