# Generated by Django 3.2.12 on 2023-06-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rg_trendsmall', '0004_auto_20230531_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptops',
            old_name='dicount_percentage',
            new_name='discount_percentage',
        ),
    ]
