# Generated by Django 3.2.12 on 2023-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_trendsmall', '0005_rename_dicount_percentage_laptops_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='oldprice',
            field=models.IntegerField(null=True),
        ),
    ]
