# Generated by Django 4.2 on 2024-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_trendsmall', '0006_auto_20230605_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.ImageField(upload_to='images/product/large-size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/product/large-size'),
        ),
    ]
