# Generated by Django 4.2 on 2024-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_trendsmall', '0007_alter_laptops_image_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.ImageField(upload_to='images/products/large-size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/products/large-size'),
        ),
    ]
